### ISSUE TITLE
Compute detwei and dshape in tensor tabulation kernels

### ISSUE THREAD

**Issue by kynan** [gmarkall/manycore_form_compiler#16]
- Since `transform_to_physical` will change to only compute the Jacobian determinant and (if necessary) inverse. That means `detwei` and (if necessary) `dShape` need to be computed by the kernel tabulating the local tensor.
- Kernels need to take _det(J)_ and (if necessary) _inv(J)_ as parameter for each unique element

**Comment by dham** [comment]
The nice thing about this is that once we do Jacobian insertion in the UFL, the rest of the code basically just sees J, inv(J) and det(J) as tensor and scalar fields respectively so kernels taking them as parameters should "just work".

**Comment by gmarkall** [comment]
This has been achieved in the generate-transforms branch, merged in e739ee4.
