### ISSUE TITLE
Errors when using more than one thread per block

### ISSUE THREAD

**Issue by gmarkall** [gmarkall/manycore_form_compiler#22]
All the tests fail when the generated code uses more than one thread per block.

I suspect this is something to do with the way transform_to_physical handles shared memory.

**Comment by kynan** [comment]
Hopefully this problem will then "magically" go away with the new `transform_to_physical` which won't use shared memory.

**Comment by gmarkall** [comment]
I woulnd't like to count on it - I could have made some other error. I hope to look at this today since it's not a problem I want to leave you with.

**Comment by gmarkall** [comment]
Looks like there was another error - in generated forms, the arrays for storing the values of coefficients at quadrature points were **shared**, but there was no logic to ensure that each thread used an offset into the shared memory for its own element data. As a result, all threads overwrote each others results. The **shared** keyword is now removed and is being tested by the buildbot.

**Comment by gmarkall** [comment]
Fixed and tested since revision  c6346ba9b237bb9715e8
