### ISSUE TITLE
Crash when there's no solve

### ISSUE THREAD

**Issue by gmarkall** [gmarkall/manycore_form_compiler#4]
There's a hard-coded implicit assumption that there is a solve() in the source at the moment. Using an input file without a solve() causes a crash at the moment. This is probably invalid input, and should be identified as such, instead of just dying.

**Comment by kynan** [comment]
Thinking about it, I don't think a solve is absolutely necessary. There could be other (arithmetic) operations expressed in UFL you want to do to a field and we should think about how to handle those. I'll open another issue to track that.

**Comment by kynan** [comment]
An input file without a `solve` doesn't cause a crash any more. I fixed that in 8d7f9fe4e2bf5269da2e. A _no-op_ test extracting a field from state and writing it back without modification was added in ddda427e96e8f07f19bc.

However, currently only one `solve` is supported per UFL equation, see issue #31
