### ISSUE TITLE
In branch global-vector-assembly, BasisIndex objects are being constructed with the wrong extent

### ISSUE THREAD

**Issue by gmarkall** [gmarkall/manycore_form_compiler#50]
E.g. in identity-vector, the Local tensor expressions look like:

localTensor[((i_ele + n_ele \* i_r_0) + 3 \* n_ele \* i_r_1)] = 0.0;

That should be 6 \* n_ele \* ..., not 3 \* n_ele \* ...

The root of the problem is that basis indices are only constructed using a count, and they are not given the relevant element for the basis functions that they are iterating over. They need to be passed the element, so that they know whether they are indexing over a FiniteElement, VectorElement etc. to choose the correct upper bound for the index.

(This is next on my list to fix - just keeping track of it here).

**Comment by kynan** [comment]
That's a symptom of a more general issue: Our current construction of the various indices in the backend is not ideal. Upon construction of an index, its extent is set to a related attribute of the form:
- `numGaussPoints` for a `GaussIndex`
- `numDimensions` for a `DimIndex`
- `numNodesPerEle` for a `BasisIndex`

There's several issues with this approach:
- We shouldn't use attributes of the form in the first place, but of the `Element`. The current abstraction is flawed in this point.
- Having the functions constructing indices bound to the `FormBackend` makes it difficult to build arbitrary expressions (see #51)

**Comment by gmarkall** [comment]
So, it looks like:
- we need to pass a count and an element for a BasisIndex
- We should pass a count and the number of dimensions for a DimIndex
- we need to pass the number of gauss points for a gauss index - or if we pass no count of gauss points, use some default value such as numGaussPoints in the FormBackend?

**Comment by kynan** [comment]
I don't like the thought of adding an additional parameter too much, but I don't see a way around it at the moment. It's tricky to set defaults if the constructors are not bound to an object (which we'd ideally want) to take the default from. That may be a problem for the gauss index - it is going to be tricky to supply the parameter when constructing the index.

**Comment by gmarkall** [comment]
Fixed by 3ed68d1e3a
